---
# tasks file for ansible-maestro-java
- name: Ensure that maestro exporter dependencies are installed (RPM-based)
  tags:
    - maestro
    - dependencies
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
  package: name="{{ maestro_exporter_dependencies }}" state=present

- debug:
    msg: "Going to download & use maestro from {{ maestro_exporter_download_url }}"

- name: Download Maestro exporter from {{ maestro_exporter_download_url }}
  tags:
    - maestro
    - download
  get_url:
    url: "{{ maestro_exporter_download_url }}"
    dest: "{{ maestro_exporter_download_dest }}/{{ maestro_exporter_download_url | basename}}"
    force: yes
  register: dist_get

- name: Unzip downloaded distribution to {{ maestro_exporter_install_dest }}
  tags:
    - maestro
    - unarchive
  unarchive:
    src: "{{ maestro_exporter_download_dest }}/{{ maestro_exporter_download_url | basename }}"
    dest: "{{ maestro_exporter_install_dest }}/"
    remote_src: True
  register: dist_unzipped
  when: dist_get.changed

- name: Create link to maestro install dir {{ maestro_exporter_install_dest }}/{{ maestro_exporter_install_link }}
  tags:
    - maestro
    - link
  file:
    src: "{{ maestro_exporter_install_dest }}/maestro-exporter-1.2.0-SNAPSHOT"
    dest: "{{ maestro_exporter_install_dest }}/{{ maestro_exporter_install_link }}"
    state: link
    mode: 0755
    owner: "{{ maestro_user }}"
    group: "{{ maestro_user }}"
    force: true

- name: Configure maestro java
  tags:
    - maestro
    - configure
  template:
    src: templates/maestro-exporter-service.conf.j2
    dest: "{{ maestro_exporter_install_dest }}/{{ maestro_exporter_install_link }}/config/maestro-exporter-service.conf"
    owner: "{{ maestro_user }}"
    group: "{{ maestro_user }}"
    mode: 0755
  notify: "restart maestro exporter service"

- name: Ensure correct ownership
  tags:
    - maestro
    - ownership
  shell: chown -R "{{ maestro_user }}":"{{ maestro_user }}" {{ maestro_exporter_install_dest }}/maestro*
